### PR TITLE
Add `@ember/test-waiters` to default `allowedVersions` list

### PR DESCRIPTION
**Pull request by Turbo87**
see https://github.com/emberjs/ember-test-waiters/pull/86 and https://github.com/emberjs/ember-test-helpers/pull/1109#issuecomment-902008310

### CODE REVIEW

**Comment by Turbo87** [comment]
@dfreeman friendly reminder :)

**Comment by dfreeman** [comment]
Thanks!

**Comment by dfreeman** [comment]
Just released in v2.0.1! (Apparently we've been treating additions like this as bugfixes in the past, so ¯\\\_(ツ)_/¯)

**Comment by Turbo87** [comment]
sweet, thank you! ❤️

**Pull request merged**
